import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — RepostAI",
  description: "Terms and conditions for using RepostAI.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-20">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm text-muted mb-8">Last updated: 25 March 2026</p>

      <div className="prose prose-sm space-y-6 text-foreground/90">
        <section>
          <h2 className="text-xl font-semibold mb-3">1. Service Description</h2>
          <p className="text-muted leading-relaxed">
            RepostAI is an AI-powered content repurposing tool. You provide content, and we generate platform-optimised versions for Twitter/X, LinkedIn, Instagram, Email, and Reddit. The service is provided &ldquo;as is&rdquo; without guarantees of specific results.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">2. Free &amp; Paid Plans</h2>
          <p className="text-muted leading-relaxed">
            The free tier provides up to 3 reposts per day at no cost, with no account required. Paid plans (Pro and Agency) provide unlimited reposts and additional features. Paid subscriptions are billed monthly or annually through Stripe.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">3. Payments &amp; Refunds</h2>
          <p className="text-muted leading-relaxed">
            All payments are processed securely by Stripe. Subscriptions renew automatically unless cancelled. You can cancel anytime through the customer portal — your access continues until the end of the billing period. Refund requests are handled on a case-by-case basis within 14 days of purchase.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">4. Your Content</h2>
          <p className="text-muted leading-relaxed">
            You retain full ownership of the content you provide and the outputs generated. By using RepostAI, you confirm that you have the right to use and repurpose the content you submit. We do not claim any rights over your input or output content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">5. AI-Generated Content</h2>
          <p className="text-muted leading-relaxed">
            Outputs are generated by AI and may not always be perfect. You are responsible for reviewing and editing generated content before posting. RepostAI is not liable for any consequences arising from the use of AI-generated content on social media or other platforms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">6. Acceptable Use</h2>
          <p className="text-muted leading-relaxed">
            You agree not to use RepostAI to generate spam, misleading content, hate speech, or content that violates any applicable laws. We reserve the right to suspend accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">7. Availability</h2>
          <p className="text-muted leading-relaxed">
            We aim for high uptime but do not guarantee uninterrupted service. We may perform maintenance or updates that temporarily affect availability. We are not liable for any losses caused by service downtime.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
          <p className="text-muted leading-relaxed">
            To the maximum extent permitted by law, RepostAI shall not be liable for indirect, incidental, or consequential damages. Our total liability is limited to the amount you have paid us in the 12 months preceding any claim.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">9. Changes to Terms</h2>
          <p className="text-muted leading-relaxed">
            We may update these terms from time to time. Continued use of RepostAI after changes constitutes acceptance of the updated terms. Material changes will be communicated via the website.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">10. Contact</h2>
          <p className="text-muted leading-relaxed">
            Questions about these terms? Contact us at{" "}
            <a href="mailto:hello@repostai.shop" className="text-primary hover:underline">
              hello@repostai.shop
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
